services:
  backend:
    build: ./backend
    env_file:
      - ./backend/backend/.env
    # ports:
    #   - "8000:8000"
    healthcheck:
      test: ["CMD", "healthyurl", "http://localhost:8000"]
      start_interval: 7s
      interval: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    env_file:
    - ./backend/backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_interval: 5s
      interval: 5s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data

  directus:
    image: directus/directus:11.6.1
    environment:
      # LOG_LEVEL: debug
      SECRET: ${ADMIN_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: "pg"
      DB_HOST: "db"
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PUBLIC_URL: "http://admin.localhost"
      
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://directus:8055/server/health"]
      start_interval: 5s
      interval: 5s
      retries: 10

    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_healthy
  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          target: /app/frontend

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro 
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend: 
        condition: service_healthy
      directus:
        condition: service_healthy
      frontend: 
        condition: service_started

volumes:
  db-data: {}
