services:
  backend:
    build: ./backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/backend/.env

    ports:
      - "8000:8000"
    depends_on:
      db:
        restart: true
        condition: service_healthy
      redis:
        restart: true
        condition: service_healthy
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis
    hostname: redis
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 3s
      retries: 10
      start_period: 5s
    volumes:
      - redis-data:/data

volumes:
  db-data: {}
  redis-data: {}
